CREATE TABLE email_verification_tokens (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           token VARCHAR(255) NOT NULL UNIQUE,
                                           user_id BIGINT NOT NULL UNIQUE,
                                           expires_at TIMESTAMP NOT NULL,
                                           CONSTRAINT fk_email_verification_user
                                               FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_email_verification_token ON email_verification_tokens (token);